# 2db9b8161b7cbcd39f483407ff8b635960d945ca encoding: utf-8
# @@ 1

########################### DO NOT MODIFY THIS FILE ###########################
#       This file was automatically generated by JRubyFX-fxmlloader on        #
# 2014-12-08 10:56:45 +0100 for /home/vpereira/urna/lib/views/urna.fxml
########################### DO NOT MODIFY THIS FILE ###########################

module JRubyFX
  module GeneratedAssets
    class AOT2d739f68421990c3610b3638273bfaea8eb1cf5e
      include JRubyFX
          def __build_via_jit(__local_fxml_controller, __local_namespace, __local_jruby_ext)
      __local_fx_id_setter = lambda do |name, __i|
        __local_namespace[name] = __i
        __local_fxml_controller.instance_variable_set(("@#{name}").to_sym, __i)
      end

build(Java::JavafxSceneControl::SplitPane) do
 __local_jruby_ext[:on_root_set].call(self) if __local_jruby_ext[:on_root_set]
 getItems.add(build(Java::JavafxSceneLayout::AnchorPane) do
  getChildren.add(build(Java::JavafxSceneControl::Label) do
   setLayoutX(14.0)
   setLayoutY(14.0)
   setText("MEU VOTO PARA")
  end)
  getChildren.add(build(Java::JavafxSceneControl::Label) do
   setId("cargo_label")
   __local_fx_id_setter.call("cargo_label", self)
   setFont(build(FxmlBuilderBuilder, {"size"=>"17.0"}, Java::JavafxSceneText::Font) do
   end)
   setLayoutX(14.0)
   setLayoutY(40.0)
   setText("DEPUTADO FEDERAL")
  end)
  getChildren.add(build(Java::JavafxSceneImage::ImageView) do
   setId("foto")
   __local_fx_id_setter.call("foto", self)
   setImage(build(FxmlBuilderBuilder, {"url"=>"file:/home/vpereira/urna/lib/views/images/pol1.png"}, Java::JavafxSceneImage::Image) do
   end)
   setFitHeight(166.0)
   setFitWidth(141.0)
   setLayoutX(241.0)
   setLayoutY(1.0)
   setPickOnBounds(true)
   setPreserveRatio(true)
  end)
  getChildren.add(build(Java::JavafxSceneLayout::HBox) do
   setId("input_hbox")
   __local_fx_id_setter.call("input_hbox", self)
   getChildren.add(build(Java::JavafxSceneControl::TextField) do
    setId("input_1")
    __local_fx_id_setter.call("input_1", self)
    setLayoutX(89.0)
    setLayoutY(190.0)
    setPrefHeight(30.0)
    setPrefWidth(30.0)
   end)
   getChildren.add(build(Java::JavafxSceneControl::TextField) do
    setId("input_2")
    __local_fx_id_setter.call("input_2", self)
    setLayoutX(127.0)
    setLayoutY(190.0)
    setPrefHeight(30.0)
    setPrefWidth(30.0)
   end)
   setPadding(build(FxmlBuilderBuilder, {"left"=>"10.0"}, Java::JavafxGeometry::Insets) do
   end)
   setLayoutX(89.0)
   setLayoutY(190.0)
   setPrefHeight(32.0)
   setPrefWidth(205.0)
   setSpacing(5.0)
  end)
  getChildren.add(build(Java::JavafxSceneLayout::VBox) do
   getChildren.add(build(Java::JavafxSceneControl::Label) do
    setLayoutX(12.0)
    setLayoutY(195.0)
    setStyle("-fx-font-size: 18px; -fx-font-weight: bold;")
    setText("Numero:")
   end)
   getChildren.add(build(Java::JavafxSceneControl::Label) do
    setLayoutX(14.0)
    setLayoutY(239.0)
    setStyle("-fx-font-size: 18px; -fx-font-weight: bold;")
    setText("Nome:")
   end)
   getChildren.add(build(Java::JavafxSceneControl::Label) do
    setLayoutX(15.0)
    setLayoutY(286.0)
    setStyle("-fx-font-size: 18px; -fx-font-weight: bold;")
    setText("Partido:")
   end)
   setLayoutX(12.0)
   setLayoutY(195.0)
   setSpacing(20.0)
  end)
  getChildren.add(build(Java::JavafxSceneLayout::Pane) do
   getChildren.add(build(Java::JavafxSceneLayout::VBox) do
    getChildren.add(build(Java::JavafxSceneControl::Label) do
     setLayoutX(14.0)
     setLayoutY(21.0)
     setText("Aperte a Tecla:")
    end)
    getChildren.add(build(Java::JavafxSceneControl::Label) do
     setLayoutX(14.0)
     setLayoutY(53.0)
     setText("VERDE para CONFIRMAR")
    end)
    getChildren.add(build(Java::JavafxSceneControl::Label) do
     setLayoutX(14.0)
     setLayoutY(89.0)
     setText("LARANJA para CORRIGIR")
    end)
    setLayoutX(13.98095703125)
    setLayoutY(21.0)
    setSpacing(5.0)
   end)
   setLayoutX(1.0)
   setLayoutY(325.0)
   setPrefHeight(153.0)
   setPrefWidth(386.0)
   setStyle("-fx-border-color: black; -fx-border-style: solid; -fx-border-width: 5 0 0 0;")
  end)
  getChildren.add(build(Java::JavafxSceneControl::Label) do
   setId("nome_candidato")
   __local_fx_id_setter.call("nome_candidato", self)
   setLayoutX(103.0)
   setLayoutY(233.0)
   setPrefHeight(32.0)
   setPrefWidth(272.0)
  end)
  getChildren.add(build(Java::JavafxSceneControl::Label) do
   setId("nome_partido")
   __local_fx_id_setter.call("nome_partido", self)
   setLayoutX(87.0)
   setLayoutY(277.0)
   setPrefHeight(21.0)
   setPrefWidth(288.0)
  end)
  setMinHeight(0.0)
  setMinWidth(0.0)
  setPrefHeight(398.0)
  setPrefWidth(327.0)
 end)
 getItems.add(build(Java::JavafxSceneLayout::AnchorPane) do
  getChildren.add(build(Java::JavafxSceneLayout::HBox) do
   getChildren.add(build(Java::JavafxSceneImage::ImageView) do
    setImage(build(FxmlBuilderBuilder, {"url"=>"file:/home/vpereira/urna/lib/views/img/tse-logo.gif"}, Java::JavafxSceneImage::Image) do
    end)
    setFitHeight(133.0)
    setFitWidth(384.0)
    setPickOnBounds(true)
    setPreserveRatio(true)
   end)
   setPadding(build(FxmlBuilderBuilder, {"top"=>"5.0"}, Java::JavafxGeometry::Insets) do
   end)
   setLayoutX(2.0)
   setPrefHeight(100.0)
   setPrefWidth(385.0)
  end)
  getChildren.add(build(Java::JavafxSceneLayout::VBox) do
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setStyle("-fx-text-fill: #fff; -fx-font-weight: bold; -fx-font-size: 25px; -fx-background-color: #000; -fx-alignment: center; -fx-background-radius: 5,4,3,5; -fx-border-radius: 5,4,3,5; -fx-border-color: #fff;")
    setText("3")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_3"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setStyle("-fx-text-fill: #fff; -fx-font-weight: bold; -fx-font-size: 25px; -fx-background-color: #000; -fx-alignment: center; -fx-background-radius: 5,4,3,5; -fx-border-radius: 5,4,3,5; -fx-border-color: #fff;")
    setText("6")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_6"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setStyle("-fx-text-fill: #fff; -fx-font-weight: bold; -fx-font-size: 25px; -fx-background-color: #000; -fx-alignment: center; -fx-background-radius: 5,4,3,5; -fx-border-radius: 5,4,3,5; -fx-border-color: #fff;")
    setText("9")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_9"))
   end)
   setPadding(build(FxmlBuilderBuilder, {"left"=>"25.0", "top"=>"8.0"}, Java::JavafxGeometry::Insets) do
   end)
   setLayoutX(253.0)
   setLayoutY(140.0)
   setPrefHeight(200.0)
   setPrefWidth(74.0)
   setSpacing(18.0)
  end)
  getChildren.add(build(Java::JavafxSceneLayout::VBox) do
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setStyle("-fx-text-fill: #fff; -fx-font-weight: bold; -fx-font-size: 25px; -fx-background-color: #000; -fx-alignment: center; -fx-background-radius: 5,4,3,5; -fx-border-radius: 5,4,3,5; -fx-border-color: #fff;")
    setText("2")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_2"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setStyle("-fx-text-fill: #fff; -fx-font-weight: bold; -fx-font-size: 25px; -fx-background-color: #000; -fx-alignment: center; -fx-background-radius: 5,4,3,5; -fx-border-radius: 5,4,3,5; -fx-border-color: #fff;")
    setText("5")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_5"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setStyle("-fx-text-fill: #fff; -fx-font-weight: bold; -fx-font-size: 25px; -fx-background-color: #000; -fx-alignment: center; -fx-background-radius: 5,4,3,5; -fx-border-radius: 5,4,3,5; -fx-border-color: #fff;")
    setText("8")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_8"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setStyle("-fx-text-fill: #fff; -fx-font-weight: bold; -fx-font-size: 25px; -fx-background-color: #000; -fx-alignment: center; -fx-background-radius: 5,4,3,5; -fx-border-radius: 5,4,3,5; -fx-border-color: #fff;")
    setText("0")
    setTextOverrun(Java::javafx::scene::control::OverrunStyle::WORD_ELLIPSIS)
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_0"))
   end)
   setPadding(build(FxmlBuilderBuilder, {"left"=>"13.0", "top"=>"8.0"}, Java::JavafxGeometry::Insets) do
   end)
   setLayoutX(146.0)
   setLayoutY(140.0)
   setPrefHeight(248.0)
   setPrefWidth(74.0)
   setSpacing(18.0)
  end)
  getChildren.add(build(Java::JavafxSceneLayout::VBox) do
   setPadding(build(FxmlBuilderBuilder, {"left"=>"10.0", "top"=>"8.0"}, Java::JavafxGeometry::Insets) do
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setStyle("-fx-text-fill: #fff; -fx-font-weight: bold; -fx-font-size: 25px; -fx-background-color: #000; -fx-alignment: center; -fx-background-radius: 5,4,3,5; -fx-border-radius: 5,4,3,5; -fx-border-color: #fff;")
    setText("1")
    setTextOverrun(Java::javafx::scene::control::OverrunStyle::WORD_ELLIPSIS)
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_1"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setStyle("-fx-text-fill: #fff; -fx-font-weight: bold; -fx-font-size: 25px; -fx-background-color: #000; -fx-alignment: center; -fx-background-radius: 5,4,3,5; -fx-border-radius: 5,4,3,5; -fx-border-color: #fff;")
    setText("4")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_4"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setStyle("-fx-text-fill: #fff; -fx-font-weight: bold; -fx-font-size: 25px; -fx-background-color: #000; -fx-alignment: center; -fx-background-radius: 5,4,3,5; -fx-border-radius: 5,4,3,5; -fx-border-color: #fff;")
    setText("7")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_7"))
   end)
   setLayoutX(23.0)
   setLayoutY(140.0)
   setPrefHeight(200.0)
   setPrefWidth(74.0)
   setSpacing(18.0)
  end)
  getChildren.add(build(Java::JavafxSceneLayout::HBox) do
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    Java::JavafxSceneLayout::HBox.setMargin(self, build(FxmlBuilderBuilder, {"top"=>"30.0"}, Java::JavafxGeometry::Insets) do
    end)
    setMnemonicParsing(false)
    setPrefHeight(49.0)
    setPrefWidth(87.0)
    setStyle("-fx-background-color: #ffffff; -fx-border-color: #000000; -fx-alignment: center; -fx-background-radius: 5.4.3.5; -fx-border-radius: 5,4,3,5; -fx-font-size: 15px;")
    setText("BRANCO")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_branco"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    Java::JavafxSceneLayout::HBox.setMargin(self, build(FxmlBuilderBuilder, {"top"=>"30.0"}, Java::JavafxGeometry::Insets) do
    end)
    setMnemonicParsing(false)
    setPrefHeight(40.0)
    setPrefWidth(104.0)
    setStyle("-fx-background-color: #ff7d05; -fx-alignment: center; -fx-border-color: #000000; -fx-border-radius: 5,4,3,5; -fx-background-radius: 5,4,3,5; -fx-font-size: 15px;")
    setText("CORRIGE")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_corrige"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setId("confirma")
    __local_fx_id_setter.call("confirma", self)
    Java::JavafxSceneLayout::HBox.setMargin(self, build(FxmlBuilderBuilder, {"top"=>"10.0"}, Java::JavafxGeometry::Insets) do
    end)
    setMnemonicParsing(false)
    setPrefHeight(52.0)
    setPrefWidth(111.0)
    setStyle("-fx-background-color: #0fe20f; -fx-border-color: #000000; -fx-alignment: center; -fx-background-radius: 5,4,3,5; -fx-border-radius: 5,4,3,5; -fx-font-size: 15px;")
    setText("CONFIRMA")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_confirma"))
   end)
   setPadding(build(FxmlBuilderBuilder, {"left"=>"10.0", "top"=>"20.0"}, Java::JavafxGeometry::Insets) do
   end)
   setLayoutY(382.0)
   setPrefHeight(82.0)
   setPrefWidth(385.0)
   setSpacing(30.0)
  end)
  setPadding(build(FxmlBuilderBuilder, {"left"=>"5.0"}, Java::JavafxGeometry::Insets) do
  end)
  setMinHeight(0.0)
  setMinWidth(0.0)
  setPrefHeight(486.0)
  setPrefWidth(412.0)
  setStyle("-fx-background-color: #44413d;")
 end)
 setDividerPositions(*[0.5])
 setMaxHeight(-Infinity)
 setMaxWidth(-Infinity)
 setMinHeight(-Infinity)
 setMinWidth(-Infinity)
 setPrefHeight(480.0)
 setPrefWidth(781.0)
end
    end

      def hash
        "2db9b8161b7cbcd39f483407ff8b635960d945ca"
      end
      def compiled?
        true
      end
    end
  end
end
