# 37917603d676d183e8d8e11dc260a3467d2eb381 encoding: utf-8
# @@ 1

########################### DO NOT MODIFY THIS FILE ###########################
#       This file was automatically generated by JRubyFX-fxmlloader on        #
# 2014-12-08 10:56:51 +0100 for /home/vpereira/urna/lib/views/fim.fxml
########################### DO NOT MODIFY THIS FILE ###########################

module JRubyFX
  module GeneratedAssets
    class AOT49dc186c0348b598f0296a6235dc48082fd2bf15
      include JRubyFX
          def __build_via_jit(__local_fxml_controller, __local_namespace, __local_jruby_ext)
      __local_fx_id_setter = lambda do |name, __i|
        __local_namespace[name] = __i
        __local_fxml_controller.instance_variable_set(("@#{name}").to_sym, __i)
      end

build(Java::JavafxSceneLayout::Pane) do
 __local_jruby_ext[:on_root_set].call(self) if __local_jruby_ext[:on_root_set]
 getChildren.add(build(Java::JavafxSceneControl::Label) do
  setFont(build(FxmlBuilderBuilder, {"name"=>"Arial Bold", "size"=>"96.0"}, Java::JavafxSceneText::Font) do
  end)
  setAlignment(Java::javafx::geometry::Pos::CENTER)
  setLayoutX(217.0)
  setLayoutY(146.0)
  setText("FIM")
  setTextAlignment(Java::javafx::scene::text::TextAlignment::CENTER)
  setTextFill(RubyWrapperBeanAdapter.coerce("#8507ab", Java::JavafxScenePaint::Paint.java_class))
  setWrapText(true)
 end)
 setMaxHeight(-Infinity)
 setMaxWidth(-Infinity)
 setMinHeight(-Infinity)
 setMinWidth(-Infinity)
 setPrefHeight(400.0)
 setPrefWidth(600.0)
end
    end

      def hash
        "37917603d676d183e8d8e11dc260a3467d2eb381"
      end
      def compiled?
        true
      end
    end
  end
end
