# 03d6fa409021c52580d51ce308e2e0c6ef13cfe0 encoding: utf-8
# @@ 1

########################### DO NOT MODIFY THIS FILE ###########################
#       This file was automatically generated by JRubyFX-fxmlloader on        #
# 2014-11-11 23:40:51 +0000 for /home/vpereira/urna/app/views/urna.fxml
########################### DO NOT MODIFY THIS FILE ###########################

module JRubyFX
  module GeneratedAssets
    class AOT2d739f68421990c3610b3638273bfaea8eb1cf5e
      include JRubyFX
          def __build_via_jit(__local_fxml_controller, __local_namespace, __local_jruby_ext)
      __local_fx_id_setter = lambda do |name, __i|
        __local_namespace[name] = __i
        __local_fxml_controller.instance_variable_set(("@#{name}").to_sym, __i)
      end

build(Java::JavafxSceneControl::SplitPane) do
 __local_jruby_ext[:on_root_set].call(self) if __local_jruby_ext[:on_root_set]
 getItems.add(build(Java::JavafxSceneLayout::AnchorPane) do
  getChildren.add(build(Java::JavafxSceneControl::Label) do
   setLayoutX(14.0)
   setLayoutY(29.0)
   setText("MEU VOTO PARA")
  end)
  getChildren.add(build(Java::JavafxSceneControl::Label) do
   setId("cargo_label")
   __local_fx_id_setter.call("cargo_label", self)
   setFont(build(FxmlBuilderBuilder, {"size"=>"17.0"}, Java::JavafxSceneText::Font) do
   end)
   setLayoutX(14.0)
   setLayoutY(54.0)
   setText("DEPUTADO FEDERAL")
  end)
  getChildren.add(build(Java::JavafxSceneImage::ImageView) do
   setImage(build(FxmlBuilderBuilder, {"url"=>"file:/home/vpereira/urna/app/views/images/pol1.png"}, Java::JavafxSceneImage::Image) do
   end)
   setFitHeight(120.0)
   setFitWidth(118.0)
   setLayoutX(274.0)
   setLayoutY(14.0)
   setPickOnBounds(true)
   setPreserveRatio(true)
  end)
  getChildren.add(build(Java::JavafxSceneLayout::HBox) do
   setId("input_hbox")
   __local_fx_id_setter.call("input_hbox", self)
   getChildren.add(build(Java::JavafxSceneControl::TextField) do
    setId("input_1")
    __local_fx_id_setter.call("input_1", self)
    setLayoutX(89.0)
    setLayoutY(190.0)
    setPrefHeight(25.0)
    setPrefWidth(30.0)
   end)
   getChildren.add(build(Java::JavafxSceneControl::TextField) do
    setId("input_2")
    __local_fx_id_setter.call("input_2", self)
    setLayoutX(127.0)
    setLayoutY(190.0)
    setPrefHeight(25.0)
    setPrefWidth(30.0)
   end)
   setLayoutX(89.0)
   setLayoutY(190.0)
   setPrefHeight(25.0)
   setPrefWidth(197.0)
   setSpacing(5.0)
  end)
  getChildren.add(build(Java::JavafxSceneControl::Label) do
   setLayoutX(14.0)
   setLayoutY(195.0)
   setText("Numero")
  end)
  getChildren.add(build(Java::JavafxSceneControl::Label) do
   setLayoutX(14.0)
   setLayoutY(239.0)
   setText("Nome")
  end)
  getChildren.add(build(Java::JavafxSceneControl::Label) do
   setLayoutX(14.0)
   setLayoutY(274.0)
   setText("Partido")
  end)
  setMinHeight(0.0)
  setMinWidth(0.0)
  setPrefHeight(398.0)
  setPrefWidth(327.0)
 end)
 getItems.add(build(Java::JavafxSceneLayout::AnchorPane) do
  getChildren.add(build(Java::JavafxSceneLayout::HBox) do
   getChildren.add(build(Java::JavafxSceneImage::ImageView) do
    setImage(build(FxmlBuilderBuilder, {"url"=>"file:/home/vpereira/urna/app/views/img/tse-logo.gif"}, Java::JavafxSceneImage::Image) do
    end)
    setFitHeight(133.0)
    setFitWidth(384.0)
    setPickOnBounds(true)
    setPreserveRatio(true)
   end)
   setPadding(build(FxmlBuilderBuilder, {"top"=>"5.0"}, Java::JavafxGeometry::Insets) do
   end)
   setLayoutX(2.0)
   setPrefHeight(100.0)
   setPrefWidth(385.0)
  end)
  getChildren.add(build(Java::JavafxSceneLayout::VBox) do
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setText("3")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_3"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setText("6")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_6"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setText("9")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_9"))
   end)
   setPadding(build(FxmlBuilderBuilder, {"left"=>"25.0", "top"=>"8.0"}, Java::JavafxGeometry::Insets) do
   end)
   setLayoutX(253.0)
   setLayoutY(140.0)
   setPrefHeight(200.0)
   setPrefWidth(74.0)
   setSpacing(18.0)
  end)
  getChildren.add(build(Java::JavafxSceneLayout::VBox) do
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setText("2")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_2"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setText("5")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_5"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setText("8")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_8"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setText("0")
    setTextOverrun(Java::javafx::scene::control::OverrunStyle::WORD_ELLIPSIS)
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_0"))
   end)
   setPadding(build(FxmlBuilderBuilder, {"left"=>"13.0", "top"=>"8.0"}, Java::JavafxGeometry::Insets) do
   end)
   setLayoutX(146.0)
   setLayoutY(140.0)
   setPrefHeight(248.0)
   setPrefWidth(74.0)
   setSpacing(18.0)
  end)
  getChildren.add(build(Java::JavafxSceneLayout::VBox) do
   setPadding(build(FxmlBuilderBuilder, {"left"=>"10.0", "top"=>"8.0"}, Java::JavafxGeometry::Insets) do
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setText("1")
    setTextOverrun(Java::javafx::scene::control::OverrunStyle::WORD_ELLIPSIS)
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_1"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setText("4")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_4"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    setMnemonicParsing(false)
    setPrefHeight(35.0)
    setPrefWidth(47.0)
    setText("7")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_7"))
   end)
   setLayoutX(23.0)
   setLayoutY(140.0)
   setPrefHeight(200.0)
   setPrefWidth(74.0)
   setSpacing(18.0)
  end)
  getChildren.add(build(Java::JavafxSceneLayout::HBox) do
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    Java::JavafxSceneLayout::HBox.setMargin(self, build(FxmlBuilderBuilder, {"top"=>"30.0"}, Java::JavafxGeometry::Insets) do
    end)
    setMnemonicParsing(false)
    setPrefHeight(49.0)
    setPrefWidth(87.0)
    setStyle("-fx-background-color: #ffffff; -fx-border-color: #000000;")
    setText("BRANCO")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_branco"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    Java::JavafxSceneLayout::HBox.setMargin(self, build(FxmlBuilderBuilder, {"top"=>"30.0"}, Java::JavafxGeometry::Insets) do
    end)
    setMnemonicParsing(false)
    setPrefHeight(40.0)
    setPrefWidth(104.0)
    setStyle("-fx-background-color: #ff7d05; -fx-border-color: #000000;")
    setText("CORRIGE")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_corrige"))
   end)
   getChildren.add(build(Java::JavafxSceneControl::Button) do
    Java::JavafxSceneLayout::HBox.setMargin(self, build(FxmlBuilderBuilder, {"top"=>"10.0"}, Java::JavafxGeometry::Insets) do
    end)
    setMnemonicParsing(false)
    setPrefHeight(52.0)
    setPrefWidth(111.0)
    setStyle("-fx-background-color: #0fe20f; -fx-border-color: #000000;")
    setText("CONFIRMA")
    setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "click_confirma"))
   end)
   setPadding(build(FxmlBuilderBuilder, {"left"=>"10.0", "top"=>"20.0"}, Java::JavafxGeometry::Insets) do
   end)
   setLayoutY(382.0)
   setPrefHeight(82.0)
   setPrefWidth(385.0)
   setSpacing(30.0)
  end)
  setPadding(build(FxmlBuilderBuilder, {"left"=>"5.0"}, Java::JavafxGeometry::Insets) do
  end)
  setMinHeight(0.0)
  setMinWidth(0.0)
  setPrefHeight(486.0)
  setPrefWidth(412.0)
 end)
 setDividerPositions(*[0.5])
 setMaxHeight(-Infinity)
 setMaxWidth(-Infinity)
 setMinHeight(-Infinity)
 setMinWidth(-Infinity)
 setPrefHeight(480.0)
 setPrefWidth(781.0)
end
    end

      def hash
        "03d6fa409021c52580d51ce308e2e0c6ef13cfe0"
      end
      def compiled?
        true
      end
    end
  end
end
