#!/usr/bin/env ruby
require 'irb'
require "irb/completion"

require_relative "../urna"

# init db connection
Urna::Db::init(:config=>'config/database.yml',:env=>'development')


trap("SIGINT") do
  IRB.abort
end

IRB.start
